[buildPlans.curlio]
family = "Curlio"
spacing = "term"
serifs = "sans"
no-cv-ss = true

webfont-formats = ['ttf']

[buildPlans.curlio.variants]
inherits = "ss20"

[buildPlans.curlio.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
asterisk = "penta-low"
brace = "straight"
at = "fourfold-solid-inner"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
zero = "long-dotted"
four = "closed"
seven = "bend-serifless"
eight = "two-circles"

[buildPlans.curlio.variants.upright]

[buildPlans.curlio.variants.italic]
a = "double-storey-serifless"
e = "flat-crossbar"
f = "serifless"
i = "serifed"
k = "curly-serifless"
l = "serifed"
u = "toothed"
y = "curly"
long-s = "bent-hook"
eszet = "sulzbacher"
cyrl-ef = "serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"

[buildPlans.curlio.ligations]
inherits = "javascript"
disables = []
enables = []

[buildPlans.curlio.widths.normal]
shape = 600
menu = 5
css = "normal"

###################################################################################################

[buildPlans.blocky]
family = "Blocky"
spacing = "term"
serifs = "sans"
no-cv-ss = true

webfont-formats = ['ttf']

[buildPlans.blocky.variants]
inherits = "ss02"

[buildPlans.blocky.variants.design]
zero = "long-dotted"
seven = "straight-serifed"
dollar = "open"
cent = "open"

[buildPlans.blocky.variants.upright]

[buildPlans.blocky.variants.italic]

[buildPlans.blocky.ligations]
inherits = "javascript"
disables = []
enables = []

[buildPlans.blocky.widths.normal]
shape = 600
menu = 5
css = "normal"
