# make sure font patcher doesn't rename
# TTF + WOFF2, hinted + unhinted:
# npm run build -- contents::curlio
# TTF:
# npm run build -- ttf::curlio
# CSS + WOFF2:
# npm run build -- webfont::curlio
# WOFF2:
# npm run build -- woff2::curlio

[buildPlans.curlio]
family = "Curlio"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

webfont-formats = ['ttf', 'woff2']

[buildPlans.curlio.variants]
inherits = "ss20"

[buildPlans.curlio.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "flat-hook-serifed"
a = "double-storey-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifless"
k = "curly-serifless"
l = "serifed"
t = "flat-hook"
u = "toothed-serifless"
y = "curly-serifless"

long-s = "bent-hook-serifless"
eszet = "sulzbacher-serifless"

lower-iota = "serifed-flat-tailed"
lower-xi = "rounded"
lower-tau = "flat-tailed"

cyrl-ef = "serifless"
cyrl-u = "curly-serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"

zero = "long-dotted"
four = "closed"
five = "upright-flat"
seven = "curly-serifless"

asterisk = "penta-low"
brace = "straight"
guillemet = "straight"
at = "fourfold-solid-inner"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
lig-neq = "vertical"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.curlio.ligations]
inherits = "javascript"
disables = ["ltgt-slash-tag"]
enables = ["arrow-l"]

[buildPlans.curlio.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.curlio.widths.normal]
shape = 600
menu = 5
css = "normal"
